name: Tailscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ vars.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:ci
          version: 1.64.2


      - name: PostgreSQL
        run: |
          ping ${{ vars.RDS_POSTGRESQL_HOSTNAME }}
          telnet ${{ vars.RDS_POSTGRESQL_HOSTNAME }} 5432

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
